"""
PDF report generation for FinScan.
Uses ReportLab to produce a branded A4 document with logo, metrics and receipt list.
"""
from __future__ import annotations

import os
import uuid
from datetime import date, datetime
from typing import Optional

from reportlab.lib import colors
from reportlab.lib.colors import HexColor
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.platypus import (
    HRFlowable,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

# ── Paths ─────────────────────────────────────────────────────────────────────
REPORTS_DIR = os.path.join(os.path.dirname(__file__), "..", "..", "reports")
LOGO_PATH   = os.path.join(os.path.dirname(__file__), "..", "images", "playstore_icon.png")

# ── Brand colours ─────────────────────────────────────────────────────────────
INDIGO   = HexColor("#3F51B5")
INDIGO_L = HexColor("#7986CB")
WHITE    = colors.white
DARK     = HexColor("#212121")
GREY     = HexColor("#757575")
LIGHT_BG = HexColor("#F5F5F5")

# ── i18n strings ─────────────────────────────────────────────────────────────
_T: dict[str, dict[str, str]] = {
    "pt": {
        "app_tagline":    "Gestor de Recibos Financeiros",
        "page":           "Página",
        "period":         "Período",
        "all_time":       "Todo o tempo",
        "account":        "Conta",
        "summary":        "Resumo",
        "total_receipts": "Recibos",
        "total_spent":    "Total Gasto",
        "avg_receipt":    "Média por Recibo",
        "top_category":   "Categoria Principal",
        "by_category":    "Gastos por Categoria",
        "col_category":   "Categoria",
        "col_receipts":   "Recibos",
        "col_total":      "Total (€)",
        "col_percent":    "% do Total",
        "receipt_list":   "Lista de Recibos",
        "col_date":       "Data",
        "col_store":      "Loja",
        "no_receipts":    "Sem recibos no período seleccionado.",
        "generated":      "Gerado pela FinScan",
        "confidential":   "© FinScan — Confidencial",
        "na":             "—",
    },
    "en": {
        "app_tagline":    "Financial Receipt Manager",
        "page":           "Page",
        "period":         "Period",
        "all_time":       "All time",
        "account":        "Account",
        "summary":        "Summary",
        "total_receipts": "Receipts",
        "total_spent":    "Total Spent",
        "avg_receipt":    "Avg. per Receipt",
        "top_category":   "Top Category",
        "by_category":    "Spending by Category",
        "col_category":   "Category",
        "col_receipts":   "Receipts",
        "col_total":      "Total (€)",
        "col_percent":    "% of Total",
        "receipt_list":   "Receipt List",
        "col_date":       "Date",
        "col_store":      "Store",
        "no_receipts":    "No receipts found for the selected period.",
        "generated":      "Generated by FinScan",
        "confidential":   "© FinScan — Confidential",
        "na":             "—",
    },
}

def _t(locale: str, key: str) -> str:
    return _T.get(locale, _T["en"]).get(key, _T["en"].get(key, key))


# ── Styles ────────────────────────────────────────────────────────────────────
def _styles() -> dict:
    base = getSampleStyleSheet()
    return {
        "h2": ParagraphStyle(
            "h2", parent=base["Normal"],
            fontSize=13, textColor=INDIGO, fontName="Helvetica-Bold", leading=18,
        ),
        "body": ParagraphStyle(
            "body", parent=base["Normal"],
            fontSize=9, textColor=DARK, leading=13,
        ),
        "small": ParagraphStyle(
            "small", parent=base["Normal"],
            fontSize=8, textColor=GREY, leading=12,
        ),
        "metric_val": ParagraphStyle(
            "metric_val", parent=base["Normal"],
            fontSize=17, textColor=INDIGO, fontName="Helvetica-Bold", leading=21,
        ),
        "metric_lbl": ParagraphStyle(
            "metric_lbl", parent=base["Normal"],
            fontSize=7, textColor=GREY, leading=11,
        ),
        "cell": ParagraphStyle(
            "cell", parent=base["Normal"],
            fontSize=8, textColor=DARK, leading=11,
        ),
        "cell_hdr": ParagraphStyle(
            "cell_hdr", parent=base["Normal"],
            fontSize=8, textColor=WHITE, fontName="Helvetica-Bold", leading=11,
        ),
    }


def _header_footer(canvas, doc, locale: str) -> None:
    """Draws the branded header band and footer on every page."""
    canvas.saveState()
    W, H = A4

    # ── Header band ──────────────────────────────────────────────────────────
    canvas.setFillColor(INDIGO)
    canvas.rect(0, H - 3 * cm, W, 3 * cm, fill=True, stroke=False)

    # Logo (if available)
    logo_exists = os.path.exists(LOGO_PATH)
    if logo_exists:
        try:
            logo_size = 1.5 * cm
            canvas.drawImage(
                LOGO_PATH,
                1.5 * cm, H - 2.6 * cm,
                width=logo_size, height=logo_size,
                preserveAspectRatio=True, mask="auto",
            )
            text_x = 3.4 * cm
        except Exception:
            logo_exists = False

    if not logo_exists:
        text_x = 1.5 * cm

    # App name
    canvas.setFont("Helvetica-Bold", 20)
    canvas.setFillColor(WHITE)
    canvas.drawString(text_x, H - 1.75 * cm, "FinScan")

    # Tagline
    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(HexColor("#C5CAE9"))
    canvas.drawString(text_x, H - 2.35 * cm, _t(locale, "app_tagline"))

    # Page number
    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(HexColor("#C5CAE9"))
    canvas.drawRightString(W - 1.5 * cm, H - 2.05 * cm,
                           f"{_t(locale, 'page')} {doc.page}")

    # ── Footer ───────────────────────────────────────────────────────────────
    canvas.setFillColor(LIGHT_BG)
    canvas.rect(0, 0, W, 1 * cm, fill=True, stroke=False)
    canvas.setFont("Helvetica", 7)
    canvas.setFillColor(GREY)
    canvas.drawString(
        1.5 * cm, 0.35 * cm,
        f"{_t(locale, 'generated')}  ·  {datetime.utcnow().strftime('%Y-%m-%d %H:%M')} UTC",
    )
    canvas.drawRightString(W - 1.5 * cm, 0.35 * cm, _t(locale, "confidential"))

    canvas.restoreState()


def _table_style() -> TableStyle:
    return TableStyle([
        ("BACKGROUND",     (0, 0), (-1, 0),  INDIGO),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [WHITE, LIGHT_BG]),
        ("GRID",           (0, 0), (-1, -1), 0.4, HexColor("#E0E0E0")),
        ("BOX",            (0, 0), (-1, -1), 0.4, HexColor("#BDBDBD")),
        ("TOPPADDING",     (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING",  (0, 0), (-1, -1), 5),
        ("LEFTPADDING",    (0, 0), (-1, -1), 6),
        ("RIGHTPADDING",   (0, 0), (-1, -1), 6),
        ("VALIGN",         (0, 0), (-1, -1), "MIDDLE"),
    ])


def generate_pdf(
    receipts: list,
    date_from: Optional[date],
    date_to: Optional[date],
    username: str,
    locale: str = "en",
) -> str:
    """
    Build a branded PDF from *receipts* and write it to REPORTS_DIR.
    Returns the GUID filename (e.g. "abc123.pdf").
    """
    os.makedirs(REPORTS_DIR, exist_ok=True)
    filename = f"{uuid.uuid4()}.pdf"
    filepath = os.path.join(REPORTS_DIR, filename)

    st = _styles()
    W, _ = A4

    doc = SimpleDocTemplate(
        filepath,
        pagesize=A4,
        leftMargin=1.5 * cm,
        rightMargin=1.5 * cm,
        topMargin=3.8 * cm,
        bottomMargin=1.6 * cm,
    )

    # Wrap header/footer so we can pass locale without a global
    def _page_template(canvas, doc):
        _header_footer(canvas, doc, locale)

    story = []

    # ── Period + account sub-header ───────────────────────────────────────────
    if date_from or date_to:
        from_s = date_from.strftime("%d %b %Y") if date_from else _t(locale, "na")
        to_s   = date_to.strftime("%d %b %Y")   if date_to   else _t(locale, "na")
        period_label = f"{_t(locale, 'period')}: {from_s} → {to_s}"
    else:
        period_label = f"{_t(locale, 'period')}: {_t(locale, 'all_time')}"

    story.append(Spacer(1, 0.3 * cm))
    story.append(Paragraph(period_label, st["small"]))
    story.append(Paragraph(f"{_t(locale, 'account')}: {username}", st["small"]))
    story.append(Spacer(1, 0.5 * cm))

    # ── Metrics ───────────────────────────────────────────────────────────────
    total_amount = sum(r.total for r in receipts)
    n_receipts   = len(receipts)
    avg_amount   = total_amount / n_receipts if n_receipts else 0.0

    cat_map: dict[str, dict] = {}
    for r in receipts:
        cn = r.category_name or _t(locale, "na")
        if cn not in cat_map:
            cat_map[cn] = {"count": 0, "total": 0.0}
        cat_map[cn]["count"] += 1
        cat_map[cn]["total"] += r.total

    top_category = (
        max(cat_map, key=lambda k: cat_map[k]["total"]) if cat_map else _t(locale, "na")
    )

    story.append(Paragraph(_t(locale, "summary"), st["h2"]))
    story.append(Spacer(1, 0.3 * cm))

    col_w = (W - 3 * cm) / 4
    metrics_data = [[
        [Paragraph(str(n_receipts),          st["metric_val"]), Paragraph(_t(locale, "total_receipts"), st["metric_lbl"])],
        [Paragraph(f"€{total_amount:.2f}",   st["metric_val"]), Paragraph(_t(locale, "total_spent"),    st["metric_lbl"])],
        [Paragraph(f"€{avg_amount:.2f}",     st["metric_val"]), Paragraph(_t(locale, "avg_receipt"),    st["metric_lbl"])],
        [Paragraph(top_category,             st["metric_val"]), Paragraph(_t(locale, "top_category"),   st["metric_lbl"])],
    ]]
    mt = Table(metrics_data, colWidths=[col_w] * 4, rowHeights=[2.2 * cm])
    mt.setStyle(TableStyle([
        ("BACKGROUND",    (0, 0), (-1, -1), LIGHT_BG),
        ("BOX",           (0, 0), (-1, -1), 0.5, HexColor("#E0E0E0")),
        ("INNERGRID",     (0, 0), (-1, -1), 0.5, HexColor("#E0E0E0")),
        ("ALIGN",         (0, 0), (-1, -1), "CENTER"),
        ("VALIGN",        (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING",    (0, 0), (-1, -1), 8),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
    ]))
    story.append(mt)
    story.append(Spacer(1, 0.7 * cm))

    # ── By category ───────────────────────────────────────────────────────────
    story.append(Paragraph(_t(locale, "by_category"), st["h2"]))
    story.append(Spacer(1, 0.25 * cm))

    cat_rows = [[
        Paragraph(_t(locale, "col_category"), st["cell_hdr"]),
        Paragraph(_t(locale, "col_receipts"), st["cell_hdr"]),
        Paragraph(_t(locale, "col_total"),    st["cell_hdr"]),
        Paragraph(_t(locale, "col_percent"),  st["cell_hdr"]),
    ]]
    for cn, data in sorted(cat_map.items(), key=lambda x: x[1]["total"], reverse=True):
        pct = (data["total"] / total_amount * 100) if total_amount else 0
        cat_rows.append([
            Paragraph(cn,                       st["cell"]),
            Paragraph(str(data["count"]),       st["cell"]),
            Paragraph(f"{data['total']:.2f}",  st["cell"]),
            Paragraph(f"{pct:.1f}%",            st["cell"]),
        ])
    cw = W - 3 * cm
    cat_table = Table(cat_rows, colWidths=[cw * 0.4, cw * 0.2, cw * 0.2, cw * 0.2])
    cat_table.setStyle(_table_style())
    story.append(cat_table)
    story.append(Spacer(1, 0.7 * cm))

    # ── Receipt list ──────────────────────────────────────────────────────────
    story.append(Paragraph(_t(locale, "receipt_list"), st["h2"]))
    story.append(Spacer(1, 0.25 * cm))

    if not receipts:
        story.append(Paragraph(_t(locale, "no_receipts"), st["body"]))
    else:
        rec_rows = [[
            Paragraph(_t(locale, "col_date"),     st["cell_hdr"]),
            Paragraph(_t(locale, "col_store"),    st["cell_hdr"]),
            Paragraph(_t(locale, "col_category"), st["cell_hdr"]),
            Paragraph(_t(locale, "col_total"),    st["cell_hdr"]),
        ]]
        for r in sorted(receipts, key=lambda x: x.purchase_date, reverse=True):
            rec_rows.append([
                Paragraph(r.purchase_date.strftime("%d/%m/%Y"), st["cell"]),
                Paragraph(r.store or _t(locale, "na"),          st["cell"]),
                Paragraph(r.category_name or _t(locale, "na"), st["cell"]),
                Paragraph(f"{r.total:.2f}",                     st["cell"]),
            ])
        rec_table = Table(
            rec_rows,
            colWidths=[cw * 0.18, cw * 0.37, cw * 0.26, cw * 0.19],
            repeatRows=1,
        )
        rec_table.setStyle(_table_style())
        story.append(rec_table)

    story.append(Spacer(1, 1 * cm))
    doc.build(story, onFirstPage=_page_template, onLaterPages=_page_template)
    return filename
